feat: branch and result_file params were supported (#18)
feat: branch and result_file params were supported

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -20,7 +20,7 @@ jobs:
       - name: Setup Marathon Cloud
         uses: MarathonLabs/setup-marathon-cloud@2.0.1
         with:
-          version: "1.0.30"
+          version: "1.0.38"
 
       - name: Run Marathon Cloud action-invoke
         uses: ./
@@ -29,7 +29,7 @@ jobs:
           application: "example/app.apk"
           testApplication: "example/appTest.apk"
           platform: "android"
-          name: "android_3_0"
+          name: "android_3_0_simple"
 
       - name: Show failure message
         if: failure()
@@ -53,7 +53,7 @@ jobs:
       - name: Setup Marathon Cloud
         uses: MarathonLabs/setup-marathon-cloud@2.0.1
         with:
-          version: "1.0.30"
+          version: "1.0.38"
 
       - name: Run Marathon Cloud action-invoke
         uses: ./
@@ -62,8 +62,10 @@ jobs:
           application: "example/app.apk"
           testApplication: "example/appTest.apk"
           platform: "android"
-          name: "android_3_0"
+          name: "android_3_0_output"
           output: "output"
+          resultFile: "some-result.json"
+          branch: "develop"
 
       - name: Check if output folder exists and is not empty
         run: |
@@ -74,12 +76,26 @@ jobs:
             exit 1
           fi
 
+      - name: Check if resultFile exists
+        run: |
+          if [ ! -f "some-result.json" ]; then
+            echo "Error: some-result.json does not exist."
+            exit 1
+          fi
+
       - name: Upload artifact
         if: always()
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4
         with:
           name: android_output
           path: output
+
+      - name: Upload resultFile
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: some-result.json
+          path: some-result.json
 
       - name: Show failure message
         if: failure()
@@ -103,7 +119,7 @@ jobs:
       - name: Setup Marathon Cloud
         uses: MarathonLabs/setup-marathon-cloud@2.0.1
         with:
-          version: "1.0.30"
+          version: "1.0.38"
 
       - name: Run Marathon Cloud action-invoke
         uses: ./
@@ -112,7 +128,7 @@ jobs:
           application: "example/app.apk"
           testApplication: "example/appTestFailed.apk"
           platform: "android"
-          name: "android_3_0"
+          name: "android_3_0_failed"
           output: "output"
           ignoreTestFailures: "true"
 
@@ -127,7 +143,7 @@ jobs:
 
       - name: Upload artifact
         if: always()
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4
         with:
           name: android_failed_output
           path: output
@@ -154,7 +170,7 @@ jobs:
       - name: Setup Marathon Cloud
         uses: MarathonLabs/setup-marathon-cloud@2.0.1
         with:
-          version: "1.0.30"
+          version: "1.0.38"
 
       - name: Run Marathon Cloud action-invoke
         uses: ./
@@ -177,7 +193,7 @@ jobs:
 
       - name: Upload artifact
         if: always()
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v4
         with:
           name: ios_output
           path: output
